=== dhruvbansal1207/IncidentOS/data/schemas/metric.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Metric",
  "type": "object",
  "properties": {
    "ts": {
      "type": "string",
      "format": "date-time",
      "description": "ISO 8601 UTC"
    },
    "service": {
      "type": "string"
    },
    "name": {
      "type": "string",
      "description": "error_rate, latency_p95_ms, request_count, cpu_percent"
    },
    "value": {
      "type": "number"
    }
  },
  "required": [
    "ts",
    "service",
    "name",
    "value"
  ]
}

=== dhruvbansal1207/IncidentOS/data/mock/incident_01/metrics.json
[
  {
    "ts": "2026-10-05T10:28:00Z",
    "service": "payment",
    "name": "error_rate",
    "value": 0.01
  },
  {
    "ts": "2026-10-05T10:30:00Z",
    "service": "payment",
    "name": "error_rate",
    "value": 0.01
  },
  {
    "ts": "2026-10-05T10:31:00Z",
    "service": "payment",
    "name": "error_rate",
    "value": 0.02
  },
  {
    "ts": "2026-10-05T10:32:00Z",
    "service": "payment",
    "name": "error_rate",
    "value": 0.3
  },
  {
    "ts": "2026-10-05T10:34:00Z",
    "service": "payment",
    "name": "error_rate",
    "value": 0.35
  },
  {
    "ts": "2026-10-05T10:30:00Z",
    "service": "order",
    "name": "error_rate",
    "value": 0.01
  },
  {
    "ts": "2026-10-05T10:33:00Z",
    "service": "order",
    "name": "error_rate",
    "value": 0.12
  },
  {
    "ts": "2026-10-05T10:35:00Z",
    "service": "order",
    "name": "error_rate",
    "value": 0.28
  },
  {
    "ts": "2026-10-05T10:30:00Z",
    "service": "payment",
    "name": "latency_p95_ms",
    "value": 120
  },
  {
    "ts": "2026-10-05T10:32:00Z",
    "service": "payment",
    "name": "latency_p95_ms",
    "value": 4800
  },
  {
    "ts": "2026-10-05T10:34:00Z",
    "service": "payment",
    "name": "latency_p95_ms",
    "value": 5000
  },
  {
    "ts": "2026-10-05T10:30:00Z",
    "service": "user",
    "name": "error_rate",
    "value": 0.01
  },
  {
    "ts": "2026-10-05T10:34:00Z",
    "service": "user",
    "name": "error_rate",
    "value": 0.01
  }
]
