=== dhruvbansal1207/IncidentOS/data/schemas/span.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Span",
  "type": "object",
  "properties": {
    "trace_id": {
      "type": "string"
    },
    "span_id": {
      "type": "string"
    },
    "parent_span_id": {
      "type": [
        "string",
        "null"
      ]
    },
    "service": {
      "type": "string"
    },
    "operation": {
      "type": "string"
    },
    "start_ts": {
      "type": "string",
      "format": "date-time",
      "description": "ISO 8601 UTC"
    },
    "duration_ms": {
      "type": "number"
    },
    "status": {
      "type": "string",
      "enum": [
        "ok",
        "error"
      ]
    }
  },
  "required": [
    "trace_id",
    "span_id",
    "service",
    "operation",
    "start_ts",
    "duration_ms",
    "status"
  ]
}

=== dhruvbansal1207/IncidentOS/data/mock/incident_01/traces.json
[
  {
    "trace_id": "t103",
    "span_id": "s1",
    "parent_span_id": null,
    "service": "order",
    "operation": "create_order",
    "start_ts": "2026-10-05T10:33:18Z",
    "duration_ms": 5100,
    "status": "error"
  },
  {
    "trace_id": "t103",
    "span_id": "s2",
    "parent_span_id": "s1",
    "service": "payment",
    "operation": "charge",
    "start_ts": "2026-10-05T10:33:19Z",
    "duration_ms": 5000,
    "status": "error"
  },
  {
    "trace_id": "t103",
    "span_id": "s3",
    "parent_span_id": "s2",
    "service": "database",
    "operation": "insert_payment",
    "start_ts": "2026-10-05T10:33:19Z",
    "duration_ms": 5000,
    "status": "error"
  }
]
